---
- name: Ensure required (ambari-server) packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-server
  notify: Reload systemd
  when: ansible_os_family == "RedHat"

- name: Ensure required (ambari-server) packages are installed (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-server
  when: ansible_os_family == "Debian"
  
- name: Ensure required (mysql-server) packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - mysql-server
  notify: Reload systemd
  when: (ansible_os_family == "RedHat" and {{ ansible_nodename }} in master-nodes)

- name: Ensure required (mysql-server) packages are installed (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - mysql-server
  when: (ansible_os_family == "Debian" and {{ ansible_nodename }} in master-nodes)
  
- name: Fix MySQL listening interface
  shell: sed -i 's/127.0.0.1/0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf;
  when: {{ ansible_nodename }} in master-nodes
  
- include: unbound-dns.yml
  when: use_dns

- meta: flush_handlers

- include: arcadia.yml
  when: arcadia and ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Run Ambari Server setup
  shell: /usr/sbin/ambari-server setup -s

- name: Make sure ambari-server is running
  command: service ambari-server restart

- name: Waiting for ambari-server to start listening on port 8080
  wait_for: host={{ ansible_nodename }} port=8080

- name: Waiting for ambari-agents to register
  uri: url=http://{{ ansible_nodename }}:8080/api/v1/hosts/{{ hostvars[item]['ansible_nodename'] | lower }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202,404
  with_items: "{{ groups['hadoop-cluster'] }}"
  register: result
  until: "result.status != 404"
  retries: 200
  delay: 5
